export const states = [
    "Abia",
    "abuja",
    "Adamawa",
    "Akwa Ibom", 
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross river",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "gombe",
    "imo",
    "jigawa",
    "kaduna",
    "kano",
    "katsina",
    "kebbi",
    "kogi",
    "kwara",
    "lagos",
    "nasarawa",
    "niger",
    "ogun",
    "osun",
    "oyo",
    "plateau",
    "rivers",
    "sokoto",
    "taraba",
    "yobe",
    "zamfara",
]

export const cardTypes = [
    "mastercard",
    "visa",
    "verve"
]
export const tabItems = [ {name: "Personal Info", path: "/personal-info"}, {name: "billing info", path: "/billing-info"}, {name: "confirm payment", path: "/confirm-payment"} ]